# MATTE — desktop bulk processor (Homebrew formula).
#
# This file is auto-updated by the release workflow at
# https://github.com/spinsoft-transcription/matte/blob/main/.github/workflows/release.yml
# on every `v*` tag push: `mislav/bump-homebrew-formula-action`
# rewrites the `version` and `sha256` fields to match the latest
# universal macOS tarball.
#
# Install:
#     brew install spinsoft-transcription/matte/matte-gui
#
# The initial placeholder version (0.0.0, dummy sha256) only
# matters before the first release is published; the workflow
# replaces both on its first successful run.
class MatteGui < Formula
  desc "Bulk chromakey + LUT + auto-frame compositor (iced desktop GUI)"
  homepage "https://github.com/spinsoft-transcription/matte"
  version "0.1.0"
  url "https://github.com/spinsoft-transcription/matte/releases/download/v#{version}/matte-gui-v#{version}-macos-universal.tar.gz"
  sha256 "f2e83b3fae770688b351ab76e19f1e2e6537c8afa4f1e2c226da9c6e2fb8900c"
  license "Apache-2.0"

  depends_on "ffmpeg"
  depends_on :macos

  def install
    libexec.install "matte-gui"
    pkgshare.install "yolo26n-pose.onnx"

    (bin / "matte-gui").write <<~SH
      #!/bin/bash
      # Wrapper generated by the matte-gui Homebrew formula.
      export MATTE_POSE_MODEL="#{opt_pkgshare}/yolo26n-pose.onnx"
      exec "#{libexec}/matte-gui" "$@"
    SH
    chmod 0755, bin / "matte-gui"
  end

  def caveats
    <<~EOS
      MATTE is unsigned (current v0.1.x releases ship without an
      Apple Developer ID). If macOS refuses to launch the binary
      the first time with "matte-gui cannot be opened because the
      developer cannot be verified", clear the quarantine bit once
      via:

          xattr -d com.apple.quarantine "#{libexec}/matte-gui"

      Or use System Settings → Privacy & Security → "Open Anyway".

      Settings persist at:
          ~/Library/Application Support/com.spinsoft.MATTE/

      Pose model is bundled at:
          #{opt_pkgshare}/yolo26n-pose.onnx
    EOS
  end

  test do
    assert_predicate bin / "matte-gui", :executable?
    assert_predicate pkgshare / "yolo26n-pose.onnx", :exist?
  end
end
